// Mocks generated by Mockito 5.4.6 from annotations
// in connexus_app/test/domain/usecases/decline_call_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:connexus_app/data/models/call_quality_metrics.dart' as _i8;
import 'package:connexus_app/data/models/telnyx_credentials.dart' as _i9;
import 'package:connexus_app/data/repositories/call_repository.dart' as _i11;
import 'package:connexus_app/data/services/media_handler.dart' as _i4;
import 'package:connexus_app/data/services/telnyx_service.dart' as _i5;
import 'package:connexus_app/data/services/webrtc_connection_manager.dart'
    as _i3;
import 'package:connexus_app/domain/models/call_record.dart' as _i12;
import 'package:connexus_app/domain/models/connection_state.dart' as _i2;
import 'package:connexus_app/domain/telephony/telnyx_connection_state.dart'
    as _i7;
import 'package:flutter_webrtc/flutter_webrtc.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeConnectionQuality_0 extends _i1.SmartFake
    implements _i2.ConnectionQuality {
  _FakeConnectionQuality_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWebRTCConnectionManager_1 extends _i1.SmartFake
    implements _i3.WebRTCConnectionManager {
  _FakeWebRTCConnectionManager_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMediaHandler_2 extends _i1.SmartFake implements _i4.MediaHandler {
  _FakeMediaHandler_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TelnyxService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTelnyxService extends _i1.Mock implements _i5.TelnyxService {
  MockTelnyxService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i7.TelnyxConnectionState> get connectionStateStream =>
      (super.noSuchMethod(
        Invocation.getter(#connectionStateStream),
        returnValue: _i6.Stream<_i7.TelnyxConnectionState>.empty(),
      ) as _i6.Stream<_i7.TelnyxConnectionState>);

  @override
  _i7.TelnyxConnectionState get connectionState => (super.noSuchMethod(
        Invocation.getter(#connectionState),
        returnValue: _i7.TelnyxConnectionState.disconnected,
      ) as _i7.TelnyxConnectionState);

  @override
  _i6.Stream<_i7.TelnyxConnectionEvent> get connectionEvents =>
      (super.noSuchMethod(
        Invocation.getter(#connectionEvents),
        returnValue: _i6.Stream<_i7.TelnyxConnectionEvent>.empty(),
      ) as _i6.Stream<_i7.TelnyxConnectionEvent>);

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  bool get isConnecting => (super.noSuchMethod(
        Invocation.getter(#isConnecting),
        returnValue: false,
      ) as bool);

  @override
  _i6.Stream<_i5.TelnyxCallState> get callStateStream => (super.noSuchMethod(
        Invocation.getter(#callStateStream),
        returnValue: _i6.Stream<_i5.TelnyxCallState>.empty(),
      ) as _i6.Stream<_i5.TelnyxCallState>);

  @override
  _i5.TelnyxCallState get callState => (super.noSuchMethod(
        Invocation.getter(#callState),
        returnValue: _i5.TelnyxCallState.idle,
      ) as _i5.TelnyxCallState);

  @override
  _i6.Stream<_i5.TelnyxCallEvent> get callEvents => (super.noSuchMethod(
        Invocation.getter(#callEvents),
        returnValue: _i6.Stream<_i5.TelnyxCallEvent>.empty(),
      ) as _i6.Stream<_i5.TelnyxCallEvent>);

  @override
  _i6.Stream<_i2.WebRTCConnectionState> get webrtcConnectionStateStream =>
      (super.noSuchMethod(
        Invocation.getter(#webrtcConnectionStateStream),
        returnValue: _i6.Stream<_i2.WebRTCConnectionState>.empty(),
      ) as _i6.Stream<_i2.WebRTCConnectionState>);

  @override
  _i6.Stream<_i2.ConnectionQuality> get connectionQualityStream =>
      (super.noSuchMethod(
        Invocation.getter(#connectionQualityStream),
        returnValue: _i6.Stream<_i2.ConnectionQuality>.empty(),
      ) as _i6.Stream<_i2.ConnectionQuality>);

  @override
  _i2.ConnectionQuality get currentQuality => (super.noSuchMethod(
        Invocation.getter(#currentQuality),
        returnValue: _FakeConnectionQuality_0(
          this,
          Invocation.getter(#currentQuality),
        ),
      ) as _i2.ConnectionQuality);

  @override
  _i3.WebRTCConnectionManager get connectionManager => (super.noSuchMethod(
        Invocation.getter(#connectionManager),
        returnValue: _FakeWebRTCConnectionManager_1(
          this,
          Invocation.getter(#connectionManager),
        ),
      ) as _i3.WebRTCConnectionManager);

  @override
  _i4.MediaHandler get mediaHandler => (super.noSuchMethod(
        Invocation.getter(#mediaHandler),
        returnValue: _FakeMediaHandler_2(
          this,
          Invocation.getter(#mediaHandler),
        ),
      ) as _i4.MediaHandler);

  @override
  set onQualityChange(void Function(_i8.CallQualityLevel)? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #onQualityChange,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<bool> connectWithStoredCredentials() => (super.noSuchMethod(
        Invocation.method(
          #connectWithStoredCredentials,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> connect(_i9.TelnyxCredentials? credentials) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [credentials],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void startQualityMonitoring({
    required _i10.RTCPeerConnection? peerConnection,
    String? callId,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #startQualityMonitoring,
          [],
          {
            #peerConnection: peerConnection,
            #callId: callId,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> stopQualityMonitoring({
    String? callerNumber,
    String? callDirection,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #stopQualityMonitoring,
          [],
          {
            #callerNumber: callerNumber,
            #callDirection: callDirection,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> forceReconnect() => (super.noSuchMethod(
        Invocation.method(
          #forceReconnect,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> reconnect() => (super.noSuchMethod(
        Invocation.method(
          #reconnect,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> refreshRegistration() => (super.noSuchMethod(
        Invocation.method(
          #refreshRegistration,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void updateCurrentCallContext({
    required String? callId,
    required String? callerNumber,
    String? callerName,
    String? direction = 'incoming',
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateCurrentCallContext,
          [],
          {
            #callId: callId,
            #callerNumber: callerNumber,
            #callerName: callerName,
            #direction: direction,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<bool> declineCall({String? reason}) => (super.noSuchMethod(
        Invocation.method(
          #declineCall,
          [],
          {#reason: reason},
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> setMute(bool? muted) => (super.noSuchMethod(
        Invocation.method(
          #setMute,
          [muted],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setSpeaker(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setSpeaker,
          [enabled],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> holdCall(String? callId) => (super.noSuchMethod(
        Invocation.method(
          #holdCall,
          [callId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> unholdCall(String? callId) => (super.noSuchMethod(
        Invocation.method(
          #unholdCall,
          [callId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> sendDtmf(
    String? callId,
    String? digit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendDtmf,
          [
            callId,
            digit,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> hangup(String? callId) => (super.noSuchMethod(
        Invocation.method(
          #hangup,
          [callId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [CallRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCallRepository extends _i1.Mock implements _i11.CallRepository {
  MockCallRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> saveCallRecord(_i12.CallRecord? record) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCallRecord,
          [record],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i12.CallRecord>> getRecentCalls({int? limit = 50}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentCalls,
          [],
          {#limit: limit},
        ),
        returnValue:
            _i6.Future<List<_i12.CallRecord>>.value(<_i12.CallRecord>[]),
      ) as _i6.Future<List<_i12.CallRecord>>);

  @override
  _i6.Future<List<_i12.CallRecord>> getCallsByStatus(_i12.CallStatus? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCallsByStatus,
          [status],
        ),
        returnValue:
            _i6.Future<List<_i12.CallRecord>>.value(<_i12.CallRecord>[]),
      ) as _i6.Future<List<_i12.CallRecord>>);
}
